# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Tests

on:
  push:
    

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'
     - run: mvn --batch-mode --update-snapshots verify
     - run: mkdir artifact && cp target/*.jar artifact
     - uses: actions/upload-artifact@v2
       with:
         name: Jokenpo
         path: artifact
    
